export const colorsForTypes = {
  grass: "bg-gradient-to-t from-green-500 to-green-100",
  poison: "bg-gradient-to-t from-purple-500 to-purple-100",
  fire: "bg-gradient-to-t from-red-500 to-red-100",
  bug: "bg-gradient-to-t from-lime-500 to-lime-100",
  flying: "bg-gradient-to-t from-cyan-500 to-cyan-100",
  water: "bg-gradient-to-t from-blue-500 to-blue-100",
  normal: "bg-gradient-to-t from-gray-500 to-gray-100",
  electric: "bg-gradient-to-t from-yellow-500 to-yellow-100",
  fairy: "bg-gradient-to-t from-pink-500 to-pink-100",
  ground: "bg-gradient-to-t from-amber-800 to-brown-500",
  fighting: "bg-gradient-to-t from-orange-500 to-orange-100",
  psychic: "bg-gradient-to-t from-teal-700 to-teal-300",
  steel: "bg-gradient-to-t from-teal-300 to-teal-50",
  rock: "bg-gradient-to-t from-gray-700 to-gray-300",
  dragon: "bg-gradient-to-t from-indigo-500 to-indigo-100",
  ghost: "bg-gradient-to-t from-violet-800 to-violet-300",
  ice: "bg-gradient-to-t from-sky-500 to-sky-100",
  dark: "bg-gradient-to-t from-neutral-800 to-neutral-400",
  stellar: "bg-gradient-to-t from-indigo-900 to-indigo-300",
  unknow: "bg-gradient-to-t from-gray-800 to-gray-400",
  shadow: "bg-gradient-to-t from-black to-gray-700",
};
